# Steps for Data Pre-processing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset= pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [5]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [6]:
dataset.isnull().any

<bound method DataFrame.any of    Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False>

In [7]:
dataset['Age'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [8]:
dataset['Salary'].isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: Salary, dtype: bool

In [9]:
dataset['Age'].fillna((dataset['Age'].mean()),inplace=True)
dataset['Salary'].fillna((dataset['Salary'].mean()),inplace=True)

In [10]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [11]:
dataset['Country'].value_counts()

France     4
Germany    3
Spain      3
Name: Country, dtype: int64

In [12]:
dataset['Age']=dataset['Age'].round()

In [13]:
dataset['Purchased'].value_counts()

Yes    5
No     5
Name: Purchased, dtype: int64

In [14]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [108]:
x= dataset.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [109]:
y=dataset.iloc[:,3:4].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [110]:
y.ndim

2

In [111]:
x.ndim

2

In [112]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [113]:
x.shape

(10, 3)

In [114]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [115]:
y.shape

(10, 1)

In [116]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [117]:
import sklearn

In [118]:
sklearn.__version__

'0.22.1'

In [119]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [120]:
ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
x= ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [121]:
x.shape

(10, 5)

In [122]:
#Removing dummy variable

In [123]:
x=x[:,1:]
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [124]:
x.shape

(10, 4)

In [125]:
from sklearn.preprocessing import LabelEncoder

In [126]:
lb= LabelEncoder()
y= lb.fit_transform(y)
y

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [128]:
y.shape

(10,)

In [129]:
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [130]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x=sc.fit_transform(x)
x

array([[-6.54653671e-01, -6.54653671e-01,  7.55609652e-01,
         7.49473254e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.71465267e+00,
        -1.43817841e+00],
       [ 1.52752523e+00, -6.54653671e-01, -1.27872403e+00,
        -8.91265492e-01],
       [-6.54653671e-01,  1.52752523e+00, -1.16247639e-01,
        -2.53200424e-01],
       [ 1.52752523e+00, -6.54653671e-01,  1.74371458e-01,
         6.63219199e-16],
       [-6.54653671e-01, -6.54653671e-01, -5.52176284e-01,
        -5.26656882e-01],
       [-6.54653671e-01,  1.52752523e+00,  2.90619097e-02,
        -1.07356980e+00],
       [-6.54653671e-01, -6.54653671e-01,  1.33684785e+00,
         1.38753832e+00],
       [ 1.52752523e+00, -6.54653671e-01,  1.62746694e+00,
         1.75214693e+00],
       [-6.54653671e-01, -6.54653671e-01, -2.61557187e-01,
         2.93712492e-01]])

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [141]:
x_train.shape

(8, 4)

In [140]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [142]:
x_test.shape

(2, 4)

In [138]:
y_test

array([0, 0])